cmake_minimum_required(VERSION 3.30)

set(V 1)
message("> Global: ${V}")
block()
    message(" > Outer: ${V}")
    set(V 2)
    block()
        message("  > Inner: ${V}")
        set(V 3)
        message("  < Inner: ${V}")
    endblock()
    message(" < Outer: ${V}")
endblock()
message("< Global: ${V}")
